#pragma once

// VC++ has a tradition of using commas instead of dots here.

#define FFEXT_VERSION_FILE_NUMBER 0,9,8,1
#define FFEXT_VERSION_FILE_TEXT "0,9,8,1"
#define FFEXT_VERSION_PROD_NUMBER 0,9,8,1
#define FFEXT_VERSION_PROD_TEXT "0,9,8,1"
#define FFEXT_COPYRIGHT_TEXT "Copyright 2023 Esselle Jaye - MIT/Expat license"
#define DD_COMPANY_TEXT  "DigitalDreamers.org - Esselle Jaye"
#define FFEXT_OUTPUT_FILENAME "ff1ext-golditems.dll"
